### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by knno** [knno/ImGui_GM#1]
- [x] Change how ImGui in GM side works:
    - [x] Write a `GameWindow` class that can be extended and use it as an extendable for winwin.
    - [x] State should create a GameWindow if not provided.
    - [x] Use getters and setters from `GameWindow`.
    - [x] Remove `ImGuiExtFlags.EXT_WINWIN` code in favor of using a `GameWindow` class.
    - [x] Update documentation + README

- [x] Scaling

- [ ] Multi viewports:
    - [x] Main viewports (game windows) should be represented by `GameWindow` instances in GM side.
    - [ ] Bind existing game windows as a main viewport (useful for *winwin* or similar.)
    - [ ] Add code to manage "main" viewports in ImGui

- [x] Manual Testing:
    - [x] IniSettingsFromMemory/Disk
